### ISSUE TITLE
Full Stack JavaScript Track Courses to be Completed

### ISSUE THREAD

**Issue by vanessacl** [vanessacl/Treehouse#2]
## TODO

*Courses left to complete the Treehouse Full Stack JavaScript Track*

* [ ] AJAX Basics
* [ ] Understanding "this" in JavaScript
* [ ] Object-Oriented JavaScript
* [ ] Object-Oriented JavaScript: Challenge
* [ ] The Module Pattern in JavaScript
* [ ] Noje.js Basics
* [ ] Exploring JavaScript Conditionals
* [ ] Build a Simple Dynamic Site with Node.js
* [ ] npm Basics
* [ ] Using npm as a Task Runner
* [ ] Gulp Basics
* [ ] Express Basics
* [ ] Mongo Basics
* [ ] Understanding Closures in JavaScript
* [ ] User Authentication With Express and Mongo
* [ ] Build a REST API With Express
* [ ] JavaScript Unit Testing

:sweat_smile: :ok_woman: :computer:
